#!/bin/bash

# must run as root

# The puppet manifest in manifests/simple.pp takes care of installing necessary
# packages and creating the MySQL database and user.

# Apache vhost
cp /vagrant/alephrx.conf /etc/httpd/conf.d

# Set up an alias for perl because the Aleph Rx CGI scripts use
# /usr/local/bin/perl in their shebang lines.
[ -e /usr/local/bin/perl ] || ln -s `which perl` /usr/local/bin/perl

# Start servers...
/etc/init.d/httpd start

# ... and ensure they start automatically on server startup
/sbin/chkconfig httpd on

# Create the tables.
mysql -ualephrx -palephrx alephrx < /apps/git/alephrx/docs/aleph16.sql

# Create the Apache password file for HTTP Basic authentication to the
# application.
htpasswd -b -c /apps/git/alephrx/passwd itdstaff itdstaff
htpasswd -b /apps/git/alephrx/passwd usmai usmai
htpasswd -b /apps/git/alephrx/passwd 3ALL 3ALL
htpasswd -b /apps/git/alephrx/passwd maryland maryland

# mailing works out of the box, so no need to set anything up
