#!/usr/bin/perl

## Jamie Bush, 2004
## RxWeb (AlephRx) version 3.1
## name changed 6/20/06 

=head1 NAME

ALEPHemail.cgi - Emailer and Report Confirmation Page

=head1 DESCRIPTION

This form receives the emailing options generated by ALEPHform.cgi and sends the
email to the mailer program (set in the environment variable C<ALEPHRX_MAILER>)
and then displays the full record.

This file and F<ALEPHform.cgi> must be in the same directory

=cut

############################################################################
## update 20080109 - JB, added "dlcooper@umd.edu" as bcc, see sub bcc_create
##    2009/09/23 - Hans - removed dlcooper
##    2010/09/07 - Hans - Changed aleph@itd.umd.edu to usmaialeph@umd.edu
##    2011/04/21 - Hans - Changed typo "Your have submitted ..."
############################################################################

use FindBin qw{$Bin};
use lib "$Bin/../lib";

use CGI;
use DBI;
use CGI::Carp qw(fatalsToBrowser);
use URI;
use URI::Escape;

use AlephRx::Util;

# get db connection info from the environment
# use SetEnv in the Apache config for the cgi-bin directory to set these
$database  = $ENV{ALEPHRX_DATABASE_NAME};
$db_server = $ENV{ALEPHRX_DATABASE_HOST};
$user      = $ENV{ALEPHRX_DATABASE_USER};
$password  = $ENV{ALEPHRX_DATABASE_PASS};

$statement = "";
$id = "";
$rname = "";
$response = "";
$from = $AlephRx::Util::FROM;
$mailprog = $ENV{ALEPHRX_MAILER};
$query = new CGI;
$email_check = 0;

$input_size = $ENV { 'CONTENT_LENGTH' };
read ( STDIN, $form_info, $input_size );
@input_pairs = split (/[&;]/, $form_info);

%input = ();

foreach $pair (@input_pairs) {
    #Convert plusses to spaces
    $pair =~ s/\+/ /g;

    #Split the name and value pair
    ($name, $value) = split (/=/, $pair);

    #Decode the URL encoded name and value
    $name =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;
    $value =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

    #Copy the name and value into the hash
    $input{$name} = $value;
}

$name = $query->param('name');
$campus = $query->param('campus');
$status = $query->param('status');
$escaped_text = $query->param('text');
$text = uri_unescape($escaped_text);
$escaped_summary = $query->param('summary');
$summary = uri_unescape($escaped_summary);
$date = $query->param('date');
$grp = $query->param('grp');
$time = $query->param('time');
$hour = $query->param('ampm');
$phone = $query->param('phone');
$email = $query->param('email');
$email1 = $query->param('email1');
$email2 = $query->param('email2');
$email3 = $query->param('email3');
$email3a = $query->param('email3a');
$email4 = $query->param('email4');
$email4a = $query->param('email4a');
$email5 = $query->param('email5');
$cataloger = $query->param('cataloger');
$email_config = $query->param('email_config');

#to be used in email before single quotes are escaped
$summary_mail = $summary;
$name_mail = $name;
$text_mail = $text;

if ($email3) { &Check_Email($email3a);}
if ($email4) { &Check_Email($email4a);}

if ($email_config eq "yes") {
    &Check_Email;
    if ($email_check gt 1) {
        &bad_email_display;
    } else {
        &recipient;
        &slug;
        &email_options;
        &insert_data;
        &display_record;
        if ($email_count > 0) {
            &mail;
        }
    }
} else {
    # We can get here is someone goes the ALEPHemail.cgi page directly
    # (see LIBILS-64). Provide a page indicating an error. 
    &unknown_submission_display;
}


=head2 display_record()

Displays the full report record after email configuration is confirmed and the
email is sent.

=cut
sub display_record {
    print "Content-type: text/html\n\n";
    print "<HTML>\n<HEAD>\n<TITLE>Report #$id - AlephRx</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#98AFC7\">\n";
    print "<FORM ACTION=\"ALEPH16\/ALEPHsum.cgi\" METHOD=\"post\">\n";
    print "<center>\n";
    print "<H1>AlephRx Report #$id</H1>\n";
    print "<FONT SIZE=+1 COLOR=\"#FF0000\">You have submitted report number #$id</FONT>\n";
    print "<P><INPUT TYPE=\"button\" VALUE=\"Submit a Report\" onClick=\"parent.location ='ALEPHform.cgi'\">\n";
    print "<INPUT TYPE=\"button\" VALUE=\"View Reports\" onClick=\"parent.location='ALEPH16/ALEPHsum.cgi?id'\"></p>\n";
    print "<TABLE BORDER=0 CELLPADDING=2>\n";

    $dbh = DBI->connect("DBI:mysql:$database:$db_server", $user, $password, { RaiseError => 1 });

    $statement =   "SELECT people.id, report.summary, people.name, people.phone, DATE_FORMAT(report.date,'%m/%d/%y'), people.grp, people.campus, report.status, report.text FROM people, report WHERE people.id = ? and people.id = report.id";

    $sth = $dbh->prepare($statement);
    $sth->execute($id);

    while (@row = $sth->fetchrow_array) {
        print " <TR><TD COLSPAN=7 ALIGN=RIGHT VALIGN=TOP><a href=\"ALEPH16/ALEPHreply.cgi?$row[0]\">Reply to This Report</a></FONT></TD></TR>\n";
        print "<TR><TD BGCOLOR=\"#FFFF00\" COLSPAN=7><B><i>Report #</i>&nbsp;$row[0]&nbsp;&nbsp;&nbsp;&nbsp;$row[1]</B></TD></FONT></TR>\n";
        print "<TR>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Name</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Phone</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Date</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Group</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Campus</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Status</I></TH>\n
        <TH BGCOLOR=\"#CCCCCC\"><FONT SIZE=-1><I>Text</I></TH>\n";

        print "<TR>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[2]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[3]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[4]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[5]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[6]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[7]</TD>\n";
        print "<TD BGCOLOR=\"#E8E8E8\" VALIGN=TOP>$row[8]</TD>\n";
        print "<TD VALIGN=TOP>$row[9]</TD>\n";
        $row_id = $row[0];
        $date = $row[4];
        $stext = $row[8];
        $ssummary = $row[1];
        print "</TR>\n";
        print "</TR>\n";
        print "<TR><TD><FONT SIZE=-2>&nbsp;</TD></TR>\n";
    }
    print "</TABLE>\n";
    $sth->finish;
    $dbh->disconnect;
    print "</FORM>\n";
    print "</BODY>\n</HTML>\n";
}

=head2 mail()

Formats and submits the confirmation email to the mailer prog. This function
retireves the path to the mailer from the C<$mailprog> variable, but it is
ultimately set via the C<ALEPHRX_MAILER> environment variable.

Calls C<bcc_create()> to create a Bcc header (stored in C<$bcc>), if needed.

=cut
sub mail {

    &bcc_create;

    # construct the URLs relative to the request, so the hostname and the path
    # to the script gets adjusted for whatever server this is running on
    my $reply_url = URI->new_abs('ALEPH16/ALEPHreply.cgi', $query->url);
    $reply_url->query($id);
    my $details_url = URI->new_abs('ALEPH16/ALEPHsum_full.cgi', $query->url);
    $details_url->query($id);

    open (MAIL,"|$mailprog");
    print MAIL "To: $final_email_list\n";
    print MAIL "Bcc: $bcc\n" if $bcc;
    print MAIL <<END;
From: $from
Reply-To: $AlephRx::Util::REPLY_TO
Subject: NEW:$slug#$id:$ssummary

--------------------------------------------------------------------------------
Please do not reply directly to this e-mail. 
To REPLY to this Rx: $reply_url
(If prompted, sign in with the standard USMAI username/password.)
--------------------------------------------------------------------------------

        Reported by: $name_mail
           Report# : $id
    Date of problem: $date
   Functional Group: $grp
             Campus: $campus
             Status: $status

     Problem Report: $stext 

===================================================================================
View this Rx online: $details_url
END
    close (MAIL);
}

=head2 bcc_create()

Ensure that usmaialeph@umd.edu will always receive the notification email. If
they are not in the C<$final_email_list> (as constructed by L<email_options()>),
then this function sets C<$bcc> to usmaialeph@umd.edu. Otherwise, C<$bcc> is set
to the empty string.

=cut
sub bcc_create {
    if ($final_email_list =~ /usmaialeph\@umd.edu/i) {
        $bcc = '';
    }else{
        $bcc = "usmaialeph\@umd.edu";
    }
}

=head2 email_options()

Assembles the the final list of email addresses and places it into the
C<$final_email_list> variable.

If C<$email1> is set, include the C<$recipient> set by L<recipient()>.

If C<$email2> is set, include the C<$email>, which comes from the C<email>
request parameter.

If C<$email3> is set, include the value of C<$email3a>, which comes from a
request parameter.

If C<$email4> is set, include the value of C<$email4a>, which comes from a
request parameter.

If C<$email5> is set, include it in the list.

If no emails are selected, the default C<$final_email_list> value is
"jamieb@kitabu.umd.edu".

=cut
sub email_options {
    if ($email1) {
        $recipient =~ s/\s+//g;
        $rec1 = "$recipient";
        $email_count++;
    }

    if ($email2) {
        $email =~ s/\s+//g;
        $rec2 = ",$email";
        $email_count++;
    }

    if ($email3) {
        $email3a =~ s/\s+//g;
        $rec3 = ",$email3a";
        $email_count++;
    }

    if ($email4) {
        $email4a =~ s/\s+//g;
        $rec4 = ",$email4a";
        $email_count++;
    }

    if ($email5) {
        $rec5 = ",$email5";
        $email_count++;
    }

    $final_email_list = $rec1 . $rec2 . $rec3 . $rec4 . $rec5;

    if ($email_count < 1) {
        $final_email_list = "jamieb\@kitabu.umd.edu";
    }
}

=head2 Check_Email()

Checks if its first argument is a valid email address. If it is not, it
increments the C<$email_check> counter, and pushes the bad string onto the
C<@store> array.

=cut
sub Check_Email {
    if ($_[0] =~ /(@.*@)|(,)|\s+|(\.\.)|(@\.)|(\.@)|(^\.)|(\.$)|(^\d+)|(\d+$)/ || ($_[0] !~ /^.+\@localhost$/ && $_[0] !~ /^.+\@\[?(\w|[-.])+\.[a-zA-Z]{2,3}|[0-9]{1,3}\]?$/)) {
        $email_check++; push @store, $_[0];
    } else {
    }
}

=head2 bad_email_display()

Displays error message when a bad email address is submitted. Prints all the
items in the C<@store> array.

=cut
sub bad_email_display {

    print "Content-type:  text/html\n\n";
    print "<html>\n<head>\n";
    print "<title>Error Confirming AlephRx Email Notifications</title>\n";
    print "</head>\n<body>\n";
    print "<center>\n";
    print "<h1>Error Confirming AlephRx Email Notifications</h1>\n";
    print "<h3>Not a valid email address.</h3>\n";
    print "<table>\n";
    print "<tr><td><cite><font size=+1>\n";

    foreach $store (@store) {
        print "$store<br>\n";
    }

    print "</cite></font></td></tr></table>\n";
    print "<SCRIPT=\"Javascript\">\n";
    print "<form>\n";
    print "<p><input TYPE=\"button\" VALUE=\" Back \" onClick=\"history.go(-1)\"></p>\n";
    print "</form>\n";
    print "</body>\n</html>\n";

}

=head2 unknown_submission_display()

Displays error message when a page has been called without submitting necessary
data.

=cut
sub unknown_submission_display {

    print "Content-type: text/html\n\n";
    print "<HTML>\n<HEAD>\n<TITLE>Unknown Submission Request</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#98AFC7\">\n";
    print "<h2>Unknown Submission Request</h2>\n";
    print "Submission contained no data.\n";
    print "<P><INPUT TYPE=\"button\" VALUE=\"Submit a Report\" onClick=\"parent.location ='ALEPHform.cgi'\">\n";
    print "<INPUT TYPE=\"button\" VALUE=\"View Reports\" onClick=\"parent.location='ALEPH16/ALEPHsum.cgi?id'\"></p>\n";
    print "</BODY>\n</HTML>\n";

}

=head2 recipient()

Determines the group recipient from the functional area selected in the webform
(reads the C<$grp> variable) and sets C<$recipient> accordingly.

=cut
sub recipient {
    $recipient = $AlephRx::Util::RECIPIENT_FOR{$grp};
}


=head2 slug()

Determines the slug (prefix for email) from the functional area (C<$grp>)
selected in the webform and sets the C<$slug> variable.

=cut
sub slug {
    $slug = $AlephRx::Util::SLUG_FOR{$grp};
}

=head2 insert_data()

Inserts the form data into database. Creates a new row in both the C<people> and
C<report> tables.

=cut
sub insert_data {
    $dbh = DBI->connect("DBI:mysql:$database:$db_server", $user, $password, { RaiseError => 1 });

    $statement =   "INSERT INTO people (name, grp, campus, phone, email) VALUES (?, ?, ?, ?, ?)";
    $sth = $dbh->prepare($statement);
    $sth->execute($name, $grp, $campus, $phone, $email);

    $statement =   "SELECT last_insert_id()";
    $sth = $dbh->prepare($statement);
    $sth->execute;

    $id = $sth->fetchrow_array; 

    $statement =   "INSERT INTO report (id, date, status, summary, text, cataloger, timestamp, updated, version) VALUES 
    (LAST_INSERT_ID(), NOW(), ?, ?, ?, ?, NOW(), NOW(), '18.01')";

    $sth = $dbh->prepare($statement);
    $sth->execute($status, $summary, $text, $cataloger);
    
    $sth->finish;
    $dbh->disconnect
}

